version: '3.8'

networks:
  my-network:

volumes:
  db-data:

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-fpm
    volumes:
      - .:/var/www/html
    networks:
      - my-network
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_DATABASE=your_database
      - MYSQL_USER=user
      - MYSQL_PASSWORD=userpassword

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - .:/var/www/html
    networks:
      - my-network
    depends_on:
      - php

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: your_database
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - my-network